name: dev -pipeline
on: [push]
jobs:
  push-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install Node 
        uses: actions/setup-node@v3
        with:
          node-version: '16.13.2'
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build --if-present
      - name: Test application
        run: npm test